#!/usr/bin/env ruby -I.

require "interpreter"
require "readline"

interpreter = Interpreter.new

if file = ARGV.first
  interpreter.eval File.read(file)
else
  puts "A REPL, write nice code here:\n"

  loop do
    line = Readline::readline(">>> ")
    Readline::HISTORY.push(line)
    value = interpreter.eval(line)
    puts  "=> #{value.ruby_value.inspect}"
  end
end
